services:
  - type: web
    name: shutterverse-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_CONNECTION
        fromSecret: DB_CONNECTION_STRING