services:
  - type: web
    name: shutterverse-studio
    env: node
    buildCommand: npm run install-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_CONNECTION
        fromSecret: DB_CONNECTION_STRING